### ISSUE TITLE
Error: Unable to test if File Exists (.E01)

### ISSUE THREAD

**Issue by safdar-aneela** [jarlethorsen/diskimage#1]
Hi

First of all its a great library to read disk images. Thank you for sharing.

I have used this library with .dd and .001 files and it works fine, but as soon as I gave it .E01 file or .s01 (pyewf extensions), it generates error while reading the image saying. Following is complete stack trace.

` File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "d:\worskpace\diskimagereader.py", line 41, in upload_file
    image = di.DiskImage.from_file(filename)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\diskimage\__init__.py", line 204, in from_file
    imagehandle = get_imagehandle_from_file(imagefile, imagetype)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\diskimage\__init__.py", line 448, in get_imagehandle_from_file
    filenames = pyewf.glob(imagefile)
OSError: pyewf_glob: unable to glob filenames. libcfile_file_exists_wide: unable to determine attributes of file: \\?\D:\worskpace\/ImgDest/testimage.E01 with error: The filename, directory name, or volume label syntax is incorrect.    libbfio_file_exists: unable to determine if file: \\?\D:\worskpace\/ImgDest/testimage.E01 exists.  libbfio_handle_exists: unable to determine if handle exists.  libewf_glob_wide: unable to test if file exists.
`

**Comment by jarlethorsen** [comment]
First of all, great to hear that you have found this module useful.

It is still very early in it's development as I just wanted something to use in my own projects and I figured I might as well put it "out there" just in case anybody else wanted similar features.

What is the contents of the `filename` variable in `image = di.DiskImage.from_file(filename)` ?
Is it ` \\?\D:\worskpace\/ImgDest/testimage.E01`?

Not sure how you end up with a path like this, shouldn't it be something like `D:\worskpace\ImgDest\testimage.E01`?

The actual problem seems to be that the `pyewf` module does not accept this type of path, so if this is indeed a valid path, any fix would probably have to be done within the `pyewf` module itself.

Also, the stack trace would have been easier to read with proper line-breaks :)

**Comment by safdar-aneela** [comment]
Thank you for response.

I am able to solve the issue by just replacing `di.DiskImage.from_file(filename)` by `di.DiskImage.from_file(os.path.normpath(filename))` in order to normalize any path issues, as they exist in glob function. This [link ](https://stackoverflow.com/questions/60010487/python-glob-path-issue?noredirect=1&lq=1) helped me.
